### ISSUE TITLE
App crashes while reading the OTP 

### ISSUE THREAD

**Issue by amit-jaiswal-twid** [Tkko/Flutter_Pinput#111] opened 2022-12-23 08:43 UTC
D/AndroidRuntime(13715): Shutting down VM
E/AndroidRuntime(13715): FATAL EXCEPTION: main
E/AndroidRuntime(13715): Process: com.twid, PID: 13715
E/AndroidRuntime(13715): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.twid (has extras) } in fman.ge.smart_auth.SmartAuthPlugin$ConsentBroadcastReceiver@eeba7d9
E/AndroidRuntime(13715): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1708)
E/AndroidRuntime(13715): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(13715): 	at android.os.Handler.handleCallback(Handler.java:978)
E/AndroidRuntime(13715): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(13715): 	at android.os.Looper.loopOnce(Looper.java:238)
E/AndroidRuntime(13715): 	at android.os.Looper.loop(Looper.java:357)
E/AndroidRuntime(13715): 	at android.app.ActivityThread.main(ActivityThread.java:8090)
E/AndroidRuntime(13715): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13715): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime(13715): Caused by: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
E/AndroidRuntime(13715): 	at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
E/AndroidRuntime(13715): 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:660)
E/AndroidRuntime(13715): 	at fman.ge.smart_auth.SmartAuthPlugin$ConsentBroadcastReceiver.onReceive(SmartAuthPlugin.kt:489)
E/AndroidRuntime(13715): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1698)
E/AndroidRuntime(13715): 	... 9 more

-------------------*****************-----------
As per the crash, request code that you are using in  startActivityForResult is greater than 16 bits. 
Please change the request code value to fix it.

**Comment by amit-jaiswal-twid** [comment] 2022-12-23 09:05
below are the constant , that are causing issue
        private const val HINT_REQUEST = 110101
        private const val USER_CONSENT_REQUEST = 110102
        private const val SAVE_CREDENTIAL_REQUEST = 110103
        private const val GET_CREDENTIAL_REQUEST = 110104

**Comment by Tkko** [comment] 2022-12-23 09:09
Hey @amit-jaiswal-twid, thanks for pointing out the problematic part, I'm already on it and push the update in couple of hours

**Comment by Tkko** [comment] 2022-12-23 09:19
@amit-jaiswal-twid I guess this should be okay

https://github.com/Tkko/flutter_smart_auth/blob/53014578b366c4a77fe6f159e953b44bf846cd45/android/src/main/kotlin/fman/ge/smart_auth/SmartAuthPlugin.kt#L481

**Comment by amit-jaiswal-twid** [comment] 2022-12-23 09:43
thanks @Tkko ,

**Comment by Tkko** [comment] 2022-12-23 13:33
Resolved in version [2.2.20](https://pub.dev/packages/pinput/changelog)

**Comment by AyushTripathi28** [comment] 2022-12-28 18:19
Not resolved till now

**Comment by Tkko** [comment] 2022-12-28 18:22
> Not resolved till now

Hey @AyushTripathi28, do you have the exact same error? If not please provide the logs.

**Comment by AyushTripathi28** [comment] 2022-12-28 18:28
V/AutofillManager(30990): requestHideFillUi(null): anchor = null
I/Quality (30990): Skipped: false 1 cost 19.416168 refreshRate 0 processName com.onfinance.app
W/System  (30990): Ignoring header X-Firebase-Locale because its value was null.
D/AndroidRuntime(30990): Shutting down VM
E/AndroidRuntime(30990): FATAL EXCEPTION: main
E/AndroidRuntime(30990): Process: com.onfinance.app, PID: 30990
E/AndroidRuntime(30990): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x280010 pkg=com.onfinance.app (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzyt@d1b8f55
E/AndroidRuntime(30990): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1780)
E/AndroidRuntime(30990): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(30990): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(30990): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30990): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(30990): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(30990): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(30990): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30990): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(30990): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(30990): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(30990): 	at java.util.regex.Matcher.reset(Matcher.java:256)
E/AndroidRuntime(30990): 	at java.util.regex.Matcher.<init>(Matcher.java:167)
E/AndroidRuntime(30990): 	at java.util.regex.Pattern.matcher(Pattern.java:1040)
E/AndroidRuntime(30990): 	at com.google.android.gms.internal.firebase-auth-api.zzyv.zzb(com.google.firebase:firebase-auth@@21.1.0:1)
E/AndroidRuntime(30990): 	at com.google.android.gms.internal.firebase-auth-api.zzyt.onReceive(com.google.firebase:firebase-auth@@21.1.0:8)
E/AndroidRuntime(30990): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1751)
E/AndroidRuntime(30990): 	... 9 more
I/Sentry  (30990): Not possible to read external files directory
I/TRuntime.CctTransportBackend(30990): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
W/FirebaseAuth(30990): [SmsRetrieverHelper] Timed out waiting for SMS.
I/Quality (30990): stackInfo :----- pid 30990 at 2022-12-28 23:54:09.593 -----;Cmd line: com.onfinance.app;"main" prio=5 tid=2 TIMED_WAITING sysTid=30990;  at jdk.internal.misc.Unsafe.park(Native Method);  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234);  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079);  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369);  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278);  at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:124);  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:244);  at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:170);  at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:157);  at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:54);  at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException(UncaughtExceptionHandlerIntegration.java:114);  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073);  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068);  at com.android.internal.os.RuntimeInitExtImpl.uncaughtExceptionExt(RuntimeInitExtImpl.java:43);  at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:140);  at java.lang.Thread.dispatchUncaughtException(Thread.java:2300);
I/TRuntime.CctTransportBackend(30990): Status Code: 200
I/Process (30990): Sending signal. PID: 30990 SIG: 9
Lost connection to device.
Exited

**Comment by AyushTripathi28** [comment] 2022-12-28 18:28
hey @Tkko actually it was the error I got when I tried. to fetch otp

**Comment by Tkko** [comment] 2022-12-29 08:23
Found the problem, will push the update in a few hours

**Comment by AyushTripathi28** [comment] 2022-12-29 09:44
Thanks a lot @Tkko .As I am out of deadline only this part is left. Can you please tell me any workaround of this so that app didnot crash

**Comment by Tkko** [comment] 2022-12-29 09:50
@AyushTripathi28 which `androidSmsAutofillMethod` are you using?

**Comment by AyushTripathi28** [comment] 2022-12-29 10:03
I am using smsuserconsentapi

**Comment by AyushTripathi28** [comment] 2022-12-29 10:03
<img width="515" alt="image" src="https://user-images.githubusercontent.com/37010915/209935689-b0888abf-7f2e-40dd-8d16-eda815b82ba9.png">

**Comment by Tkko** [comment] 2022-12-29 10:05
Just return `AndroidSmsAutofillMethod.none`, already pushing the update BTW

**Comment by AyushTripathi28** [comment] 2022-12-29 10:10
ohk but then auto fill will stop completely na ??

**Comment by AyushTripathi28** [comment] 2022-12-29 10:10
ohk I will wait then ✌️

**Comment by Tkko** [comment] 2022-12-29 10:12
You can also use `AndroidSmsAutofillMethod.smsRetrieverApi`, if you can send the sms containing the App signature.

**Comment by Tkko** [comment] 2022-12-29 10:14
Here you go, version [2.2.21](https://pub.dev/packages/pinput/versions/2.2.21)
It should work

**Comment by Tkko** [comment] 2022-12-29 11:12
@AyushTripathi28 please let me know if everything is okay

**Comment by AyushTripathi28** [comment] 2022-12-29 12:06
Thanks dude.
I will let you know if anything breaks otherwise its working smooth.

**Comment by AyushTripathi28** [comment] 2022-12-31 05:56
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.onfinance.app (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzyt@b177e0e
E/AndroidRuntime(15698): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1689)
E/AndroidRuntime(15698): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(15698): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(15698): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15698): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(15698): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(15698): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(15698): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15698): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(15698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(15698): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(15698): 	at java.util.regex.Matcher.reset(Matcher.java:256)
E/AndroidRuntime(15698): 	at java.util.regex.Matcher.<init>(Matcher.java:167)
E/AndroidRuntime(15698): 	at java.util.regex.Pattern.matcher(Pattern.java:1040)
E/AndroidRuntime(15698): 	at com.google.android.gms.internal.firebase-auth-api.zzyv.zzb(com.google.firebase:firebase-auth@@21.1.0:1)
E/AndroidRuntime(15698): 	at com.google.android.gms.internal.firebase-auth-api.zzyt.onReceive(com.google.firebase:firebase-auth@@21.1.0:8)
E/AndroidRuntime(15698): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
E/AndroidRuntime(15698): 	... 9 more
I/Sentry  (15698): Not possible to read external files directory
W/m.onfinance.ap(15698): Cleared Reference was only reachable from finalizer (only reported once)
W/System  (15698): A resource failed to call end.
I/TRuntime.CctTransportBackend(15698): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
W/FirebaseAuth(15698): [SmsRetrieverHelper] Timed out waiting for SMS.
I/Process (15698): Sending signal. PID: 15698 SIG: 9
Lost connection to device.
```

**Comment by AyushTripathi28** [comment] 2022-12-31 05:56
hey @Tkko , actually it was still breaking

**Comment by AyushTripathi28** [comment] 2022-12-31 05:57
any idea to fix it now as it was breaking on random 
devices

**Comment by amiejais** [comment] 2022-12-31 06:03
@AyushTripathi28  Hey Ayush, Can u share me the steps to reproduce the issue?

**Comment by AyushTripathi28** [comment] 2022-12-31 06:05
Actully it was comming randomly to any specific device, like right now one emulator with android version 12 and one mobile device with android version 11 get this error but on my device with android 11 it was working smooth

**Comment by AyushTripathi28** [comment] 2022-12-31 06:06
And as it was breaking with retriver part i am not sure where it was breaking

**Comment by AyushTripathi28** [comment] 2022-12-31 06:06
And how to reproduce that thing

**Comment by AyushTripathi28** [comment] 2022-12-31 06:21
Is there anything that i was missing in manifest file and you think should be there.

**Comment by AyushTripathi28** [comment] 2022-12-31 06:21
Like any specific permision or something else.

**Comment by AyushTripathi28** [comment] 2022-12-31 06:22
As in sentry error in 4 line from last you can see issue of external read type is it that thing ?

**Comment by amiejais** [comment] 2022-12-31 06:27
can u send  sms that you are getting  ?

**Comment by AyushTripathi28** [comment] 2022-12-31 06:29
230702 is your verification code for <app name>.

**Comment by AyushTripathi28** [comment] 2022-12-31 07:19
Any idea 🥲😅

**Comment by AyushTripathi28** [comment] 2023-01-01 10:24
Hi @Tkko Happy New Year🎉. Also any update over my problem.

**Comment by Tkko** [comment] 2023-01-01 10:31
Hey @AyushTripathi28 thanks,
Happy new year to all of you 🎊.

I won't be near the laptop till the third of January.
This issue is the first priority, I'll fix it ASAP

**Comment by AyushTripathi28** [comment] 2023-01-01 10:33
actully i just want you to read this if possible https://stackoverflow.com/questions/65803670/error-receiving-broadcast-intent-when-using-smsretriever

**Comment by AyushTripathi28** [comment] 2023-01-01 10:34
I have put timeout as 5 second in my app I didnot understand this point but want to discuss this with you.

**Comment by AyushTripathi28** [comment] 2023-01-01 10:34
No issue enjoy holidays ✌️😁

**Comment by Tkko** [comment] 2023-01-01 10:37
Are you using firebase instant verification?

**Comment by AyushTripathi28** [comment] 2023-01-01 11:25
<img width="693" alt="image" src="https://user-images.githubusercontent.com/37010915/210169096-5ec5422b-7404-4f9d-b73e-16042116a048.png">

**Comment by Tkko** [comment] 2023-01-01 11:31
You don't need any type of verification from Pinput,
Set AndroidSmsAutofillMethod to none and set pinController's value in verificationCompleted callback

**Comment by AyushTripathi28** [comment] 2023-01-02 09:20
Hi @Tkko after putting AndroidSmsAutofillMethod to none I was not able to call the firebase auth verification method.

**Comment by Tkko** [comment] 2023-01-02 09:25
Pinput has no connection to firebase auth, something else is wrong

**Comment by AyushTripathi28** [comment] 2023-01-02 09:33
ohk i will check that. Thank you

**Comment by vikranthsalian** [comment] 2023-01-29 21:08
This only crashes when we receive the OTP for the 2nd time, first time OTP it totally works fine.

**Comment by Tkko** [comment] 2023-01-30 08:43
> This only crashes when we receive the OTP for the 2nd time, first time OTP it totally works fine.

Hey @vikranthsalian, 

1. Version of Pinput?
2. Which androidSmsAutofillMethod are you using?
3. Are you switching between AndroidSmsAutofillMethod methods?
4. Could you share small reproducible code snippet?

**Comment by subash9860** [comment] 2023-02-06 07:38
app crashed while otp sms comes in android.
pinput version: 2.2.23 
log:
 D/AndroidRuntime(11134): Shutting down VM
E/AndroidRuntime(11134): FATAL EXCEPTION: main
E/AndroidRuntime(11134): Process: com.example.demo_rent, PID: 11134
E/AndroidRuntime(11134): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.example.demo_rent (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzyt@7da2aed
E/AndroidRuntime(11134): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
E/AndroidRuntime(11134): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(11134): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(11134): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11134): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(11134): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(11134): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(11134): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11134): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(11134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
E/AndroidRuntime(11134): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(11134): 	at java.util.regex.Matcher.reset(Matcher.java:256)
E/AndroidRuntime(11134): 	at java.util.regex.Matcher.<init>(Matcher.java:167)
E/AndroidRuntime(11134): 	at java.util.regex.Pattern.matcher(Pattern.java:1040)
E/AndroidRuntime(11134): 	at com.google.android.gms.internal.firebase-auth-api.zzyv.zzb(com.google.firebase:firebase-auth@@21.1.0:1)
E/AndroidRuntime(11134): 	at com.google.android.gms.internal.firebase-auth-api.zzyt.onReceive(com.google.firebase:firebase-auth@@21.1.0:8)
E/AndroidRuntime(11134): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
E/AndroidRuntime(11134): 	... 9 more
I/Process (11134): Sending signal. PID: 11134 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by Tkko** [comment] 2023-02-06 07:48
@subash9860 Are you using firebase_auth?

**Comment by subash9860** [comment] 2023-02-06 10:24
> @subash9860 Are you using firebase_auth?

yes

**Comment by Tkko** [comment] 2023-02-06 13:14
This was mentioned in the readme as well but I guess it was bit confusing.
If you are using firebase_auth
set `androidSmsAutofillMethod` to none and set controller's value in verificationCompleted:
``` dart
    Pinput(
      androidSmsAutofillMethod: AndroidSmsAutofillMethod.none,
      controller: pinController,
    );
```
And set pinController's value in `verificationCompleted` callback:
``` dart
    await FirebaseAuth.instance.verifyPhoneNumber(
      verificationCompleted: (PhoneAuthCredential credential) {
        pinController.setText(credential.smsCode);
      },
      verificationFailed: (FirebaseAuthException e) {},
      codeSent: (String verificationId, int? resendToken) {},
      codeAutoRetrievalTimeout: (String verificationId) {},
    );
```

The firebase_auth handles automatic SMS resolution on it's own and if you turn on Pinput's androidSmsAutofillMethod it both plugin is trying to read SMS and app crashes.

**Comment by faisalmushtaq007** [comment] 2023-03-31 06:51
same issue in latest version

**Comment by vaibhiarora03** [comment] 2023-04-26 17:54
Hi @Tkko , is there any solution for this issue? I am currently facing this issue.

By setting `androidSmsAutofillMethod` to `none` the app has stopped crashing. 

Please help. 

Thanks

**Comment by Tkko** [comment] 2023-04-26 17:57
@vikranthsalian Do you use firebase_auth?

**Comment by Tkko** [comment] 2023-08-02 16:42
Closing the issue for now because of inactivity, feel free to reopen it if you have the same problem.

**Closed by Tkko** 2023-08-02 16:42 UTC

**Comment by devpawann** [comment] 2023-12-13 18:16
@Tkko 
Any specific reason why we:  set pinController's value in `verificationCompleted` callback when using Firebase auth, rather than relying on SMS User Consent API or SMS Retriever API.

Because I got some crash on the emulator and reached here, now I reset emulator and its working fine. 
The whole app did crashed and it was a big concern.

**Comment by Tkko** [comment] 2023-12-13 18:23
@devpawann  The issue arises because firebase_auth and Pinput are both configured to listen for incoming SMS with a specific app signature. When these two are used simultaneously, there's a conflict between their respective listeners.

Why don't you want to set pinController's value in verificationCompleted callback?
