### ISSUE TITLE
FocusTrapArea

### ISSUE THREAD

**Issue by parameshmamidisetti** [Tkko/Flutter_Pinput#106] opened 2022-11-04 07:41 UTC
Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.
 - '_PinputState' is from 'package:pinput/src/pinput.dart' ('/C:/Users/paramesh/AppData/Local/Pub/Cache/hosted/pub.dev/pinput-2.2.16/lib/src/pinput.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FocusTrapArea'.
      child: FocusTrapArea(

**Comment by khaidem** [comment] 2022-11-05 05:43
I have also error  this when I  change flutter channel to stable it will solve

**Comment by kamami** [comment] 2022-11-18 12:21
Same issue

**Comment by Tkko** [comment] 2022-11-18 18:04
Hey guys, please take a look at https://github.com/Tkko/Flutter_Pinput/issues/98#issuecomment-1212291722

**Comment by Tkko** [comment] 2022-12-19 10:55
Duplicate of https://github.com/Tkko/Flutter_Pinput/issues/98

**Closed** 2023-01-12 16:21 UTC
