### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/pinput-2.2.17/lib/src/pinput_state.dart:339:14: Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.

### ISSUE THREAD

**Issue by johnnyychiu** [Tkko/Flutter_Pinput#110] opened 2022-12-19 10:53 UTC
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/pinput-2.2.17/lib/src/pinput_state.dart:339:14: Error: The method 'FocusTrapArea' isn't defined for the class '_PinputState'.

**Comment by Tkko** [comment] 2022-12-19 10:54
Duplicate of https://github.com/Tkko/Flutter_Pinput/issues/98

**Closed** 2023-01-12 16:21 UTC
